sudo: required

language: minimal

services:
  - docker

before_install:
  - docker pull healthcheck/redis:alpine

script:
  - docker run -d healthcheck/redis:alpine -name redis -v ./tmp:/data
  - docker exec -it redis redis-cli incr mykey
