sudo: required

language: minimal

before_install:
  - docker pull healthcheck/redis:alpine

script:
  - docker-compose start
  - docker-compose exec redis redis-cli incr mykey
  - docker-compose exec redis redis-cli incr mykey
  - docker-compose exec redis shutdown
