version: '3'
services:
  redis:
    image: "healthcheck/redis:alpine"
    volumes:
      - ./tmp:/data
    ports:
      - "6379:6379"

  runner:
    build: .
    volumes:
      - ./:/runner
    command: ["python", "test.py"]
